name: Aider Issue Processor

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  process_aider_issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'aider')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Aider CLI
        run: |
          # Download the latest Aider CLI binary for Linux from its GitHub releases.
          curl -L https://github.com/aider-ai/aider/releases/latest/download/aider-linux-amd64 -o aider
          chmod +x aider
          sudo mv aider /usr/local/bin/

      - name: Parse issue body for sections
        id: parse_issue
        shell: bash
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"

          # Extract "Description": text between "## Description" and the next markdown header.
          DESCRIPTION=$(echo "$ISSUE_BODY" | awk '/## Description/{flag=1; next} /^## /{if(flag){flag=0}} flag')
          # Extract "Files to modify": text between "## Files to modify" and the next markdown header.
          FILES=$(echo "$ISSUE_BODY" | awk '/## Files to modify/{flag=1; next} /^## /{if(flag){flag=0}} flag')
          # Extract "Acceptance criteria": text from "## Acceptance criteria" to the end.
          ACCEPTANCE=$(echo "$ISSUE_BODY" | awk '/## Acceptance criteria/{flag=1; next} flag')

          echo "ISSUE_TITLE<<EOF" >> $GITHUB_OUTPUT
          echo "$ISSUE_TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "DESCRIPTION<<EOF" >> $GITHUB_OUTPUT
          echo "$DESCRIPTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "FILES<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "ACCEPTANCE<<EOF" >> $GITHUB_OUTPUT
          echo "$ACCEPTANCE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create branch for Aider changes
        id: create_branch
        run: |
          BRANCH="aider-${{ github.event.issue.number }}"
          git checkout -b "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_ENV

      - name: Run Aider
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # Set the model to use Anthropics Sonnet 3.7. You can override by setting the AIDER_MODEL secret.
          MODEL: anthropic/claude-3-7-sonnet-20250219
        run: |
          # Build the prompt from the issue content.
          PROMPT="Issue Title: ${{ steps.parse_issue.outputs.ISSUE_TITLE }}

            Description:
            ${{ steps.parse_issue.outputs.DESCRIPTION }}

            Acceptance Criteria:
            ${{ steps.parse_issue.outputs.ACCEPTANCE }}"

          echo "Using prompt:"
          echo "$PROMPT"

          # If "Files to modify" is provided, pass them to aider; otherwise, let aider analyze the entire repository.
          if [ -n "${{ steps.parse_issue.outputs.FILES }}" ]; then
            FILES_TO_MODIFY="${{ steps.parse_issue.outputs.FILES }}"
            echo "Files to modify provided: $FILES_TO_MODIFY"
            aider --model "$MODEL" --prompt "$PROMPT" --files "$FILES_TO_MODIFY"
          else
            echo "No files provided; analyzing entire repository."
            aider --model "$MODEL" --prompt "$PROMPT"
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Aider AI: Apply changes for issue #${{ github.event.issue.number }}" || echo "No changes detected."

      - name: Push branch
        run: |
          git push --set-upstream origin ${{ env.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Aider AI Changes for Issue #${{ github.event.issue.number }}"
          body: "This PR applies the changes suggested by Aider AI for issue #${{ github.event.issue.number }} using Anthropics Sonnet 3.7."
          head: ${{ env.branch }}
          base: main
