name: Claude Code Issue Processor

# Define explicit permissions
permissions:
    contents: write
    issues: write
    pull-requests: write

on:
  issues:
    types: [labeled]
jobs:
  claude-code-issue-processor:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'claude-code')
    steps:
      - name: Parse issue description
        id: parse-description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get issue details
            const issue = context.payload.issue;
            if (!issue || !issue.body) {
              core.setFailed('No issue description found');
              return;
            }
            
            // Debug: Log issue body
            console.log('Processing issue description');
            
            // Simple markdown parser for issue descriptions
            function parseMarkdown(markdown) {
              // Function to convert basic markdown to plain text
              function markdownToPlainText(text) {
                return text
                  // Remove code blocks
                  .replace(/```[\s\S]*?```/g, '')
                  // Remove inline code
                  .replace(/`([^`]+)`/g, '$1')
                  // Remove bold/italic
                  .replace(/\*\*([^*]+)\*\*/g, '$1')
                  .replace(/\*([^*]+)\*/g, '$1')
                  .replace(/__([^_]+)__/g, '$1')
                  .replace(/_([^_]+)_/g, '$1')
                  // Handle lists by replacing bullets with spaces
                  .replace(/^\s*[*-]\s+/gm, '')
                  .replace(/^\s*\d+\.\s+/gm, '')
                  // Normalize whitespace
                  .replace(/\n+/g, ' ')
                  .replace(/\s+/g, ' ')
                  .trim();
              }
              
              // Extract sections (split by ## headings)
              const sections = {};
              const sectionRegex = /##\s+([^\n]+)([^#]*)/g;
              let match;
              
              while ((match = sectionRegex.exec(markdown)) !== null) {
                const sectionName = match[1].trim();
                const sectionContent = markdownToPlainText(match[2]);
                sections[sectionName] = sectionContent;
              }
              
              return sections;
            }
            
            try {
              // Extract sections from markdown
              const parsedSections = parseMarkdown(issue.body);
              
              // Debug: Log parsed sections
              console.log('Parsed sections:', JSON.stringify(parsedSections, null, 2));
              
              // Format the result as a single string
              let formattedResult = '';
              for (const [section, content] of Object.entries(parsedSections)) {
                formattedResult += `${section}: ${content} `;
              }
              
              // Trim extra spaces
              formattedResult = formattedResult.trim();
              
              // Add a comment to the issue with the parsed result
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `**Parsed Issue Description:**\n\n${formattedResult}`
              });
              
              // Set output for use in subsequent steps
              core.setOutput('parsed_description', formattedResult);
              
              console.log('Successfully parsed issue description');
            } catch (error) {
              console.error('Error details:', error);
              core.setFailed(`Error parsing issue description: ${error.message}`);
            }

      - name: Log parsed result
        run: |
          echo "Parsed description: ${{ steps.parse-description.outputs.parsed_description }}"
            
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create and Switch to a New Branch
        run: |
          # Extract issue number and title
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_TITLE="${{ github.event.issue.title }}"

          # Format title: lowercase, replace spaces with dashes, remove special characters
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')

          # Set branch name
          BRANCH_NAME="claude-code-issue-${ISSUE_NUMBER}-${SAFE_TITLE}"
          echo "Creating branch: $BRANCH_NAME"

          git fetch origin
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

          # Save branch name for later steps
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create run.sh script
        run: |
          mkdir -p .github/workflows
          cat > .github/workflows/run.sh << 'EOL'
          #!/bin/bash
          set -e
      
          # Debug: show environment
          echo "Current working directory: $(pwd)"
          echo "PATH: $PATH"
          echo "Node modules: $(npm root -g)"
      
          # Install claude-code if not already installed
          echo "Installing claude-code..."
          npm install -g @anthropic-ai/claude-code
      
          # Find the claude-code package directory
          CLAUDE_CODE_DIR=$(find $(npm root -g) -name "@anthropic-ai" -type d 2>/dev/null)
          if [ -z "$CLAUDE_CODE_DIR" ]; then
            echo "ERROR: Could not find @anthropic-ai directory!"
            exit 1
          fi
      
          CLAUDE_CODE_DIR="$CLAUDE_CODE_DIR/claude-code"
          echo "Found claude-code directory at: $CLAUDE_CODE_DIR"
      
          # Check for cli.js file
          if [ ! -f "$CLAUDE_CODE_DIR/cli.js" ]; then
            echo "ERROR: cli.js not found in claude-code directory!"
            ls -la "$CLAUDE_CODE_DIR"
            exit 1
          fi
      
          echo "Found cli.js at: $CLAUDE_CODE_DIR/cli.js"
      
          # Write input to file
          echo "$INPUT_TEXT" > /tmp/input.txt
      
          # Set environment variables
          export INK_DISABLE_SET_RAW_MODE=true
      
          # Run claude-code using the cli.js file directly
          echo "Running claude-code using cli.js..."
          node "$CLAUDE_CODE_DIR/cli.js" run --input-file=/tmp/input.txt --api-key="$ANTHROPIC_API_KEY" --no-interactive
          EOL
          chmod +x .github/workflows/run.sh

      - name: Build Docker image for claude-code
        run: |
          docker build -t claude-code-runner .github/workflows/
      
      - name: Run claude-code in Docker container with simulated TTY
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          INPUT_TEXT: ${{ steps.parse-description.outputs.parsed_description }}
        run: |
          docker run --rm -i \
            -e ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
            -e INPUT_TEXT="${{ steps.parse-description.outputs.parsed_description }}" \
            claude-code-runner
        
      - name: Push Claude Code Changes
        run: |
          git push origin ${{ env.BRANCH_NAME }}
    
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            ISSUE_NUMBER="${{ github.event.issue.number }}"
            ISSUE_TITLE="${{ github.event.issue.title }}"

            # Create a pull request
            gh pr create \
                --base main \
                --head ${{ env.BRANCH_NAME }} \
                --title "Fix #$ISSUE_NUMBER: $ISSUE_TITLE" \
                --body "This PR resolves issue #$ISSUE_NUMBER by applying the requested changes using Claude Code."